// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL ? (process.env.DATABASE_URL.includes('?') ? `${process.env.DATABASE_URL}&pgbouncer=true` : `${process.env.DATABASE_URL}?pgbouncer=true`) : "",
    directUrl: process.env.DIRECT_URL || "",
  },
});

if (!process.env.DATABASE_URL || !process.env.DIRECT_URL) {
  console.error("❌ Error: DATABASE_URL or DIRECT_URL is missing in .env file!");
}
